version: '3.7'

services:
  minio:
    image: minio/minio
    volumes:
    - ${HOME}/.mlad/.services/minio-data:/data
    - ${HOME}/.mlad/.services/minio-config:/root/.minio
    ports:
    - "9000:80"
    environment:
      MINIO_ACCESS_KEY: ${ACCESS_KEY:-MLAPPDEPLOY}
      MINIO_SECRET_KEY: ${SECRET_KEY:-MLAPPDEPLOY}
    networks:
      mlad-net:
    labels:
      mlappdeploy.type: "base-storage"
      mlappdeploy.description: "S3 compatible storage for MLAppDeploy"
    command: server --address ":80" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      restart_policy:
        condition: always
      placement:
        constraints:
        - node.role == manager
  registry:
    image: registry:2
    volumes:
    - ${HOME}/.mlad/.services/registry:/var/lib/registry
    ports:
    - "5000:5000"
    networks:
      mlad-net:
    labels:
      mlappdeploy.type: "base-registry"
      mlappdeploy.description: "Private docker registry for MLAppDeploy"
    deploy:
      restart_policy:
        condition: always
      placement:
        constraints:
        - node.role == manager
networks:
  mlad-net:
    name: mlad-net
    driver: overlay
    attachable: true
    ipam:
      config:
      - subnet: "10.0.9.0/24"
