version: '3.7'

services:
  minio:
    image: minio/minio
    volumes:
    - ${HOME}/.mlad/.services/minio-data:/data
    - ${HOME}/.mlad/.services/minio-config:/root/.minio
    ports:
    - "9000:80"
    environment:
      MINIO_ACCESS_KEY: ${ACCESS_KEY:-MLAPPDEPLOY}
      MINIO_SECRET_KEY: ${SECRET_KEY:-MLAPPDEPLOY}
    networks:
      mlad-net:
        aliases:
        - s3.amazonaws.com
    command: server --address ":443" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  registry:
    image: registry:2
    volumes:
    - ${HOME}/.mlad/_services/registry:/var/lib/registry
    ports:
    - "5000:5000"
    networks:
      mlad-net:
        aliases:
        - hub.docker.com
    deploy:
      restart_policy:
        condition: always

  test:
    image: ubuntu
    networks:
      mlad-net:
    command: sleep 10000000
networks:
  mlad-net:
    driver: overlay

