version: '3.7'

services:
  minio:
    image: minio/minio
    volumes:
    - ${HOME}/.mlad/.services/minio-data:/data
    - ${HOME}/.mlad/.services/minio-config:/root/.minio
    ports:
    - "9000:443"
    environment:
      MINIO_ACCESS_KEY: ${ACCESS_KEY:-MLAPPDEPLOY}
      MINIO_SECRET_KEY: ${SECRET_KEY:-MLAPPDEPLOY}
    networks:
      mlad-net:
        ipv4_address: 10.0.9.4
        aliases:
        - s3.amazonaws.com
    command: server --address ":443" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:443/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      placement:
        constraints:
        - node.role == manager
  registry:
    image: registry:2
    volumes:
    - ${HOME}/.mlad/.services/registry:/var/lib/registry
    ports:
    - "5000:5000"
    networks:
      mlad-net:
        aliases:
        - hub.docker.com
    deploy:
      restart_policy:
        condition: always
      placement:
        constraints:
        - node.role == manager
  test:
    image: ubuntu
    networks:
      mlad-net:
    command: sleep 10000000
networks:
  mlad-net:
    driver: overlay
    ipam:
      config:
      - subnet: "10.0.9.0/24"

