# MLAD CONFIG ENV
CONFIG_ENVS = {'APP', 'AWS_ACCESS_KEY_ID', 'AWS_REGION', 'AWS_SECRET_ACCESS_KEY', 'DB_ADDRESS',
               'DB_PASSWORD', 'DB_USERNAME', 'MLAD_ADDRESS', 'MLAD_SESSION', 'PROJECT',
               'PROJECT_ID', 'PROJECT_KEY', 'S3_ENDPOINT', 'S3_USE_HTTPS', 'S3_VERIFY_SSL',
               'USERNAME'}


# MLAD DEFAULT CONST
MLAD_PROJECT = 'MLAD.PROJECT'
MLAD_PROJECT_APP = 'MLAD.PROJECT.APP'
MLAD_PROJECT_APP_KIND = 'MLAD.PROJECT.APP.KIND'
MLAD_PROJECT_BASE = 'MLAD.PROJECT.BASE'
MLAD_PROJECT_ENV = 'MLAD.PROJECT.ENV'
MLAD_PROJECT_ID = 'MLAD.PROJECT.ID'
MLAD_PROJECT_IMAGE = 'MLAD.PROJECT.IMAGE'
MLAD_PROJECT_INGRESS = 'MLAD.PROJECT.INGRESS'
MLAD_PROJECT_KIND = 'MLAD.PROJECT.KIND'
MLAD_PROJECT_NAME = 'MLAD.PROJECT.NAME'
MLAD_PROJECT_NAMESPACE = 'MLAD.PROJECT.NAMESPACE'
MLAD_PROJECT_WORKSPACE = 'MLAD.PROJECT.WORKSPACE'
MLAD_PROJECT_SESSION = 'MLAD.PROJECT.SESSION'
MLAD_PROJECT_USERNAME = 'MLAD.PROJECT.USERNAME'
MLAD_PROJECT_VERSION = 'MLAD.PROJECT.VERSION'
MLAD_PROJECT_YAML = 'MLAD.PROJECT.YAML'