apiVersion: v1
entries:
  mlappdeploy:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-08-04T05:32:54.937992998Z"
    dependencies:
    - name: gpu-operator
      repository: https://nvidia.github.io/gpu-operator
      version: v1.7.1
    - name: ingress-nginx
      repository: https://kubernetes.github.io/ingress-nginx
      version: 3.35.0
    description: Machine Learning Application Deployment Tool by Kubernetes
    digest: 6481473d87c566ce81919155971cc199c17baae64a49fd434fc46a7c7407fdda
    home: https://github.com/onetop21/MLAppDeploy
    kubeVersion: '>=1.18.0'
    maintainers:
    - email: onetop21@gmail.com
      name: Hyoil LEE
    name: mlappdeploy
    type: application
    urls:
    - mlappdeploy-0.1.0.tgz
    version: 0.1.0
generated: "2021-08-04T05:32:54.929045778Z"
