apiVersion: v1
entries:
  api-server:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-08-17T06:59:33.516084676Z"
    dependencies:
    - condition: nvidia-device-plugin.enabled
      name: nvidia-device-plugin
      repository: https://nvidia.github.io/k8s-device-plugin
      version: 0.9.0
    - condition: gpu-feature-discovery.enabled
      name: gpu-feature-discovery
      repository: https://nvidia.github.io/gpu-feature-discovery
      version: 0.4.1
    - condition: dcgm-exporter.enabled
      name: dcgm-exporter
      repository: ""
      version: 2.4.0
    description: Machine Learning Application Deployment Tool by Kubernetes
    digest: 5c7883cda6e1e161437eadfc502c6c8ab5906b6309ddcbf24550bc0295170f0f
    home: https://github.com/onetop21/MLAppDeploy
    maintainers:
    - email: onetop21@gmail.com
      name: Hyoil LEE
    name: api-server
    type: application
    urls:
    - api-server-0.1.0.tgz
    version: 0.1.0
generated: "2021-08-17T06:59:33.512783232Z"
