apiVersion: v1
entries:
  api-server:
  - apiVersion: v2
    appVersion: 0.4.2
    created: "2022-04-05T14:20:41.620279256Z"
    description: Machine Learning Application Deployment Tool by Kubernetes
    digest: 399c447d4a0f5b4f1a50ac5386c023017b269457e4cd3785cbecd633dfcb1551
    home: https://github.com/onetop21/MLAppDeploy
    maintainers:
    - email: onetop21@gmail.com
      name: Hyoil LEE
    name: api-server
    type: application
    urls:
    - api-server-0.4.2.tgz
    version: 0.4.2
  - apiVersion: v2
    appVersion: 0.4.1
    created: "2022-04-05T14:20:41.619402545Z"
    description: Machine Learning Application Deployment Tool by Kubernetes
    digest: 6e94b099549555a3f6e21847526f92f4bf0e006f0dbc76ef4b77c9ebb24887c7
    home: https://github.com/onetop21/MLAppDeploy
    maintainers:
    - email: onetop21@gmail.com
      name: Hyoil LEE
    name: api-server
    type: application
    urls:
    - api-server-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2022-04-05T14:20:41.618451334Z"
    description: Machine Learning Application Deployment Tool by Kubernetes
    digest: 6c0ea30f5d6daa1b9e4c4bd292ec181c5db8356312599a790b767ab7b3c9011d
    home: https://github.com/onetop21/MLAppDeploy
    maintainers:
    - email: onetop21@gmail.com
      name: Hyoil LEE
    name: api-server
    type: application
    urls:
    - api-server-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 0.3.0
    created: "2022-04-05T14:20:41.617737725Z"
    description: Machine Learning Application Deployment Tool by Kubernetes
    digest: 0c2e62fb188c88ceaa4bace74cdc0bb147e4bd772adae72629cac98a2c354305
    home: https://github.com/onetop21/MLAppDeploy
    maintainers:
    - email: onetop21@gmail.com
      name: Hyoil LEE
    name: api-server
    type: application
    urls:
    - api-server-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2022-04-05T14:20:41.610934942Z"
    description: Machine Learning Application Deployment Tool by Kubernetes
    digest: 2167f4a29976a3ee29589a153bda98c23e316ef640d02ff30afc6ee991dea5f7
    home: https://github.com/onetop21/MLAppDeploy
    maintainers:
    - email: onetop21@gmail.com
      name: Hyoil LEE
    name: api-server
    type: application
    urls:
    - api-server-0.2.0.tgz
    version: 0.2.0
generated: "2022-04-05T14:20:41.602696141Z"
