{{- if (index .Values "dcgm-exporter" "serviceMonitorOnNamespace" "enabled") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvidia-dcgm-exporter
  {{- if (index .Values "dcgm-exporter" "serviceMonitorOnNamespace" "namespace") }}
  namespace: {{ index .Values "dcgm-exporter" "serviceMonitorOnNamespace" "namespace" }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end}}
  labels:
    app: nvidia-dcgm-exporter
    release: prometheus-stack
spec:
  endpoints:
  - port: gpu-metrics
    path: /metrics
    interval: 1s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_host_ip]
      targetLabel: host_ip
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
  namespaceSelector:
    matchNames:
    - gpu-operator-resources
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter
{{- end }}