# MLAppDeploy Project v0.3
apiVersion: v1
maintainer: root
kind: Train
name: api-use
version: 0.0.1
workdir: .
workspace:
    kind: Workspace
    base: python:latest
    preps:
      - run: pip install MLAppDeploy==0.2.0
app:
    entry:
        command: python entry.py
