# FROM python:3.9-alpine

# RUN apk --update --no-cache add \
#     zlib-dev \
#     musl-dev \
#     libc-dev \
#     libffi-dev \
#     gcc \
#     g++ \
#     git \
#     pwgen \
#     && pip install --upgrade pip

FROM python:3.9-slim

RUN apt update && apt install -y binutils
RUN pip install pyinstaller staticx patchelf

WORKDIR /build

RUN echo "pip install /build/python &&" >> build.sh
RUN echo "pyinstaller -F -n mlad-dynamic --add-data /build/python/mlad/cli/validator/schema.yaml:mlad/cli/validator --clean /build/python/mlad/cli/__main__.py &&" >> build.sh
RUN echo "staticx /build/dist/mlad-dynamic /build/dist/mlad-static" >> build.sh

CMD bash build.sh

