kind: Deployment
apiVersion: v1
name: example
version: 0.0.1
maintainer: root
workdir: .
workspace:
  kind: Workspace
  base: python:latest
  ignores:
  - '**/.*'
  env:
    PYTHONUNBUFFERED: '1'
  preps:
  - pip: requirements.txt
app:
  server:
    kind: Job
    restartPolicy: never
    command: python server.py
    expose:
    - port: 5555
  client:
    kind: Job
    restartPolicy: never
    command: python client.py
    expose:
    - port: 5555
