apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-operator
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    app.kubernetes.io/component: "gpu-operator"
    {{ $.Release.labels }}
